import React,{useMemo,useState}from'react';
import * as XLSX from'xlsx';
import{ComposedChart,Bar,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ResponsiveContainer,BarChart,LabelList}from'recharts';
import{Upload,Filter,HelpCircle,CheckSquare,CircleAlert,ChevronDown,ChevronRight,RotateCcw}from'lucide-react';
import{SAMPLE_ROWS,SKU_MASTER}from'./data';
const MENU=['Visión General','Picking','Depósito General','Repack','Plan de Acción','Ayuda'];
const AREAS={Picking:['Canchas de picking'], 'Depósito General':['Deposito general','Depósito general'], Repack:['Repack','Reproceso']};
const EMPTY=new Set(['','.', '-', 'ok','sin novedad','sin comentarios','sin comentarios adicionales','n/a','na']);
const clean=v=>{if(v==null)return'';let s=String(v).trim();return EMPTY.has(s.toLowerCase())?'':s};
const dateOf=r=>new Date(r['Hora de inicio']||r.Fecha||0);
const isQuestion=k=>k.startsWith('¿')||/^Estan todas/i.test(k)||/^La cancha/i.test(k);
const qLabel=k=>k.replace(/[0-9]+$/,'').replace(/\\xa0/g,' ').replace(/\s+/g,' ').trim();
const isAnswer=v=>['si','sí','no'].includes(String(v??'').trim().toLowerCase());
const isYes=v=>['si','sí'].includes(String(v??'').trim().toLowerCase());
const normSku=v=>clean(v).replace(/\.0$/,'');
const validSku=v=>{let s=normSku(v);return s&&/^[a-z0-9-]+$/i.test(s)&&!s.toUpperCase().endsWith('D')};
function normalize(a){return a.map((r,i)=>({...r,__id:r.Id??i+1}))}
function schema(row){const keys=Object.keys(row),out=[];for(let i=0;i<keys.length;i++){let k=keys[i];if(!isQuestion(k))continue;let extras=[];for(let j=i+1;j<keys.length&&!isQuestion(keys[j])&&!/Desea agregar/i.test(keys[j]);j++){if(/Especifique/i.test(keys[j]))extras.push(keys[j])}out.push({key:k,label:qLabel(k),extras})}return out}
function answers(r){return schema(r).filter(q=>isAnswer(r[q.key])).map(q=>({...q,ok:isYes(r[q.key]),details:q.extras.map(k=>({key:k,value:clean(r[k])})).filter(x=>x.value)}))}
function metrics(rows){let yes=0,no=0;rows.forEach(r=>answers(r).forEach(a=>a.ok?yes++:no++));return{yes,no,total:yes+no,rate:yes+no?100*yes/(yes+no):0}}
function groupName(q){let s=q.toLowerCase();if(/plaga|insect|roedor|ave|cebadera|lámpara/.test(s))return'Plagas';if(/limpio|limpieza|residuo|basura|polvo|moho|humedad/.test(s))return'Limpieza';if(/film|enfard/.test(s))return'Film stretch';if(/vencimiento|plazo|comercial/.test(s))return'Vencimiento';if(/daño|derrame|rotura|reproce/.test(s))return'Daños';if(/madera|palet|pallet/.test(s))return'Paletas';if(/identific|etiqueta|legible/.test(s))return'Identificación';if(/área|demarc|organiza|alinead|apilan|inclinación|separad/.test(s))return'Organización';if(/tijera|cuchillo|corte/.test(s))return'Herramientas';return'Otros'}
function ncQuestions(rows){let m={};rows.forEach(r=>answers(r).filter(a=>!a.ok).forEach(a=>{m[a.label]=(m[a.label]||0)+1}));let total=Object.values(m).reduce((a,b)=>a+b,0),acc=0;return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([name,value])=>{acc+=value;return{name,value,pct:total?100*value/total:0,acc:total?100*acc/total:0}})}
function ncGroups(rows){let m={};rows.forEach(r=>answers(r).filter(a=>!a.ok).forEach(a=>{let g=groupName(a.label);m[g]=(m[g]||0)+1}));return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([name,value])=>({name,value}))}
function months(rows){let m={};rows.forEach(r=>{let d=dateOf(r);if(isNaN(d))return;let k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;m[k]??={yes:0,no:0};answers(r).forEach(a=>a.ok?m[k].yes++:m[k].no++)});return Object.entries(m).sort().map(([key,x])=>({key,name:new Date(key+'-01T00:00:00').toLocaleDateString('es-AR',{month:'long'}),conformidad:x.yes+x.no?100*x.yes/(x.yes+x.no):0}))}
function weekRate(rows,offset=0){let now=new Date(Math.max(...rows.map(r=>+dateOf(r)).filter(Number.isFinite),Date.now()));let day=(now.getDay()+6)%7;let end=new Date(now);end.setHours(23,59,59,999);end.setDate(end.getDate()-day-7*offset);let start=new Date(end);start.setDate(end.getDate()-6);start.setHours(0,0,0,0);return metrics(rows.filter(r=>dateOf(r)>=start&&dateOf(r)<=end)).rate}
function areaRows(rows,page){let allowed=AREAS[page];return allowed?rows.filter(r=>allowed.includes(r.Area)):rows}
function products(rows,master){let m={};rows.forEach(r=>answers(r).filter(a=>!a.ok).forEach(a=>a.details.forEach(d=>{if(!/sku/i.test(d.key)||!validSku(d.value))return;let sku=normSku(d.value),name=master[sku]||'Descripción no encontrada',key=`${sku} | ${name}`;m[key]=(m[key]||0)+1})));return Object.entries(m).sort((a,b)=>b[1]-a[1]).map(([name,value])=>({name,value}))}
function App(){const[rows,setRows]=useState(normalize(SAMPLE_ROWS));const[master,setMaster]=useState(SKU_MASTER);const[page,setPage]=useState('Visión General');const[area,setArea]=useState('Todas');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[selected,setSelected]=useState(null);const[expanded,setExpanded]=useState({});
 const filtered=useMemo(()=>rows.filter(r=>{if(area!=='Todas'&&r.Area!==area)return false;let d=dateOf(r);return(!from||d>=new Date(from+'T00:00:00'))&&(!to||d<=new Date(to+'T23:59:59'))}),[rows,area,from,to]);
 const current=areaRows(filtered,page);const m=metrics(current);const critical=ncGroups(current)[0]?.name||'Sin datos';
 async function uploadRounds(e){let f=e.target.files[0];if(!f)return;let wb=XLSX.read(await f.arrayBuffer(),{cellDates:true});setRows(normalize(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:null})));setSelected(null)}
 function reset(){setArea('Todas');setFrom('');setTo('')}
 return <div className="app"><aside><div className="truck">🚚</div><h2>WAREHOUSE ÁREA</h2><div className="module">Rondas de Calidad</div>{MENU.map(x=><button className={page===x?'active':''} onClick={()=>setPage(x)}>{x}</button>)}<div className="back">← Volver atrás</div></aside><main><div className="topline">Archivo⌄　 Compartir⌄　 Exportar⌄ <span>↻　☰　⋯</span></div><header><div className="dpo">DPO</div><div className="title"><h1>Rondas de Calidad</h1><small>CD Mercado Central | Calidad</small></div><nav>{MENU.slice(0,-1).map(x=><button className={page===x?'on':''} onClick={()=>setPage(x)}>{x}</button>)}</nav><HelpCircle/></header><div className="filters"><Filter size={34}/><label>Área<select value={area} onChange={e=>setArea(e.target.value)}><option>Todas</option>{[...new Set(rows.map(r=>r.Area).filter(Boolean))].map(x=><option>{x}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="clear" onClick={reset}><RotateCcw size={15}/> Limpiar</button><label className="upload"><Upload size={16}/> Cargar Excel<input hidden type="file" accept=".xlsx,.xls" onChange={uploadRounds}/></label></div>
 {page!=='Plan de Acción'&&page!=='Ayuda'&&<div className="kpis"><div>Semana anterior<strong>{weekRate(current,1).toFixed(1)}%</strong></div><div>Semana actual<strong>{weekRate(current,0).toFixed(1)}%</strong></div><div>Grupo más crítico<strong>{critical}</strong></div></div>}
 {page==='Visión General'?<General rows={filtered}/>:page==='Plan de Acción'?<Plan rows={filtered} master={master} selected={selected} setSelected={setSelected}/>:page==='Ayuda'?<Help/>:<AreaPage title={page} rows={current} master={master}/>}<footer>{rows.length} rondas cargadas | Actualizado {new Date().toLocaleDateString('es-AR')}</footer></main></div>}
function General({rows}){let ar=[...new Set(rows.map(r=>r.Area).filter(Boolean))];return <div className="general grid"><Panel title="Conformidad y adherencia"><MonthChart data={months(rows)}/></Panel><Panel title="Resultado por operación"><table><thead><tr><th>Operación</th><th>Rondas</th><th>% Conformidad</th></tr></thead><tbody>{ar.map(a=><tr><td>{a}</td><td>{rows.filter(r=>r.Area===a).length}</td><td>{metrics(rows.filter(r=>r.Area===a)).rate.toFixed(1)}%</td></tr>)}</tbody></table></Panel><Panel wide title="Apertura diaria por operación, área y pregunta"><Matrix rows={rows}/></Panel></div>}
function AreaPage({title,rows,master}){let qs=ncQuestions(rows),gs=ncGroups(rows),prod=products(rows,master),aud={};rows.forEach(r=>{let n=clean(r.Nombre)||clean(r['Correo electrónico'])||'Sin identificar';aud[n]=(aud[n]||0)+1});let auditors=Object.entries(aud).sort((a,b)=>b[1]-a[1]);return <div className="areaGrid"><Panel title="Conformidad y adherencia"><MonthChart data={months(rows)}/></Panel><Panel title="Grupos de preguntas no conformes"><Bars data={gs}/></Panel><Panel title="Rondas del turno Calidad"><div className="oneTurn"><b>Turno Calidad</b><strong>{rows.length}</strong><span>rondas</span></div></Panel><Panel title="Apertura por producto"><ScrollTable heads={['SKU y descripción','Desvíos']} rows={prod.map(x=>[x.name,x.value])} empty="Sin SKU válidos informados"/></Panel><Panel large title="Pareto de preguntas"><ScrollTable heads={['Pregunta','Desvíos','% NC','% acum.']} rows={qs.map(x=>[x.name,x.value,x.pct.toFixed(1)+'%',x.acc.toFixed(1)+'%'])} empty="Sin no conformidades"/></Panel><Panel title="Rondas por funcionario"><ScrollTable heads={['Funcionario','Rondas']} rows={auditors} empty="Sin datos"/></Panel></div>}
function Matrix({rows}){let dates=[...new Set(rows.map(r=>{let d=dateOf(r);return isNaN(d)?'':d.toISOString().slice(0,10)}).filter(Boolean))].sort(),areas=[...new Set(rows.map(r=>r.Area).filter(Boolean))];return <div className="matrixWrap"><table className="matrix"><thead><tr><th>Operación</th>{dates.map(d=><th>{d.slice(8,10)+'/'+d.slice(5,7)}</th>)}</tr></thead><tbody>{areas.map(a=><tr><th>{a}</th>{dates.map(d=>{let rr=rows.filter(r=>r.Area===a&&dateOf(r).toISOString().slice(0,10)===d),mm=metrics(rr);return <td title={`${d} | ${a} | ${rr.length} rondas | ${mm.no} no conformidades`}>{!rr.length?'':mm.no?<span className="bad">●</span>:<span className="ok">✓</span>}</td>})}</tr>)}</tbody></table></div>}
function Plan({rows,master,selected,setSelected}){let rounds=rows.filter(r=>answers(r).length),r=selected||rounds[0];return <div className="plan"><div className="rounds"><h3>Selección de ronda</h3>{rounds.map(x=><button className={x.__id===r?.__id?'picked':''} onClick={()=>setSelected(x)}>{dateOf(x).toLocaleString('es-AR')} | {x.Area}<br/>{clean(x.Nombre)||clean(x['Correo electrónico'])}</button>)}</div><div className="detail"><span>Ronda seleccionada</span><h2>{r?`${dateOf(r).toLocaleString('es-AR')} | ${r.Area} | ${r.__id}`:'Sin datos'}</h2><table><thead><tr><th>Pregunta</th><th>Estado</th><th>Ítems apuntados / comentarios</th></tr></thead><tbody>{r&&answers(r).map(a=><tr><td>{a.label}</td><td>{a.ok?<CheckSquare color="#20be7b"/>:<CircleAlert color="#ee4055"/>}</td><td>{detailText(a,master)}</td></tr>)}</tbody></table>{r&&<div className="comments"><b>Comentarios de la ronda</b><p>{roundComment(r)||'Sin comentarios adicionales'}</p></div>}</div></div>}
function detailText(a,master){if(a.ok)return'';let out=[];a.details.forEach(d=>{let v=clean(d.value);if(!v)return;if(/sku/i.test(d.key)){if(!validSku(v))return;let sku=normSku(v);out.push(`SKU: ${sku} | ${master[sku]||'Descripción no encontrada'}`)}else out.push(`${d.key.replace(/[0-9]+$/,'').replace('Especifique','').trim()}: ${v}`)});return out.join(' | ')}
function roundComment(r){let vals=Object.entries(r).filter(([k])=>/Desea agregar.*comentario/i.test(k)).map(([,v])=>clean(v)).filter(Boolean);return vals.join(' | ')}
function MonthChart({data}){return <ResponsiveContainer width="100%" height={205}><ComposedChart data={data} margin={{top:22,right:10,bottom:0,left:-15}}><CartesianGrid stroke="#e5e5e5"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip formatter={v=>v.toFixed(1)+'%'} labelFormatter={x=>'Mes: '+x}/><Legend/><Bar dataKey="conformidad" fill="#f4c21d" name="% Conformidad"><LabelList dataKey="conformidad" position="top" formatter={v=>v.toFixed(1)+'%'}/></Bar><Line dataKey="conformidad" stroke="#172fa0" strokeWidth={2} name="% Adherencia pendiente" dot={{r:3}}/></ComposedChart></ResponsiveContainer>}
function Bars({data}){return <ResponsiveContainer width="100%" height={205}><BarChart data={data} margin={{top:18,right:5,bottom:42,left:-18}}><XAxis dataKey="name" angle={-28} textAnchor="end" interval={0} height={60}/><YAxis/><Tooltip/><Bar dataKey="value" fill="#f4c21d"><LabelList dataKey="value" position="top"/></Bar></BarChart></ResponsiveContainer>}
function Panel({title,children,wide=false,large=false}){return <section className={`panel${wide?' wide':''}${large?' large':''}`}><h2>{title}</h2>{children}</section>}
function ScrollTable({heads,rows,empty}){return <div className="scrollTable"><table><thead><tr>{heads.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map(r=><tr>{r.map(x=><td>{x}</td>)}</tr>):<tr><td colSpan={heads.length}>{empty}</td></tr>}</tbody></table></div>}
function Help(){return <Panel title="Ayuda"><div className="help"><h2>Uso de la aplicación</h2><p>Cargá el Excel exportado de Forms. Los gráficos, filtros, preguntas, estados, SKU y comentarios se actualizan automáticamente.</p><p>Los valores vacíos, puntos, guiones, “OK” y “Sin novedad” se omiten. Los SKU terminados en D también se excluyen.</p></div></Panel>}
export default App;